AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  CognitoIdentifier:
    Type: String
    Default: https://localhost
  CognitoUserPoolDomain:
    Type: String
    Default: macweb
  CognitoUserPoolScope:
      Type: String
      Default: macall

Resources:

  MacUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: MacUserPool
      MfaConfiguration: "OFF"
      AccountRecoverySetting: 
        RecoveryMechanisms: 
          - Name: verified_email
            Priority: 1
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      UsernameConfiguration: 
        CaseSensitive: False
      AliasAttributes: 
        - email
        - preferred_username

  MacUserPoolResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      UserPoolId: !Ref MacUserPool
      Identifier: !Ref CognitoIdentifier
      Name: "MacApi"
      Scopes: 
        - ScopeName: !Sub '${CognitoUserPoolScope}'
          ScopeDescription: !Sub '${CognitoUserPoolScope}'

  MacUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref MacUserPool
      Domain: !Ref CognitoUserPoolDomain

  MacUserPoolWebClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: "MacWebClient"
      SupportedIdentityProviders:
        - COGNITO
      UserPoolId: !Ref MacUserPool
    DependsOn: MacUserPoolResourceServer

  MacUserPoolApiClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: "MacApiClient"
      SupportedIdentityProviders:
        - COGNITO
      UserPoolId: !Ref MacUserPool
      AllowedOAuthFlows: 
        - client_credentials
      AllowedOAuthScopes: 
        - !Sub '${CognitoIdentifier}/${CognitoUserPoolScope}'
      GenerateSecret: True
    DependsOn: MacUserPoolResourceServer

Outputs: 
  CognitoUserPoolId:
    Value: !Ref MacUserPool
  CognitoWebClientId:
    Value: !Ref MacUserPoolWebClient
  CognitoApiClientId:
    Value: !Ref MacUserPoolApiClient